env:
  - CODECOV_TOKEN='00e575b7-0312-4276-b6cf-fcbfda1114cd'
language: python
python:
  - "3.8"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
install:
  - python setup.py install
# command to run tests
script:
  - python -m coverage run
  - python -m coverage run --rcfile=.bdd_coveragerc --append > /dev/null 2>&1
after_success:
  - codecov
